


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRectF
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import*
from matplotlib.backends.backend_qt5agg import FigureCanvas
from matplotlib.figure import Figure

class MplWidget(QWidget):
    
    def __init__(self, parent = None):

        QWidget.__init__(self, parent)
        
        self.canvas = FigureCanvas(Figure())
        
        vertical_layout = QVBoxLayout()
        vertical_layout.addWidget(self.canvas)
        
        self.canvas.axes = self.canvas.figure.add_subplot(111)
        self.setLayout(vertical_layout)

    def Draw(self,arr):
        self.canvas.axes.clear()
        self.canvas.axes.imshow(arr,cmap='gray')
        self.canvas.draw()
    
    def Plot(self,arr1,arr2):
        self.canvas.axes.clear()
        self.canvas.axes.bar(arr1,arr2)
        self.canvas.draw()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 786)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_79 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_79.setObjectName("gridLayout_79")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1066, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Image_label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Image_label.setFont(font)
        self.Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_label.setObjectName("Image_label")
        self.verticalLayout.addWidget(self.Image_label)
        self.Image_graphicsView = QtWidgets.QGraphicsView(self.tab_3)
        self.Image_graphicsView.setObjectName("Image_graphicsView")
        self.verticalLayout.addWidget(self.Image_graphicsView)
        self.verticalLayout_20.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Info_label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Info_label.setFont(font)
        self.Info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Info_label.setObjectName("Info_label")
        self.verticalLayout_2.addWidget(self.Info_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_20.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_20, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.NearestNeighbor_label = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NearestNeighbor_label.setFont(font)
        self.NearestNeighbor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.NearestNeighbor_label.setObjectName("NearestNeighbor_label")
        self.verticalLayout_6.addWidget(self.NearestNeighbor_label)
        self.NearestNeighbor_graphicsView = QtWidgets.QGraphicsView(self.tab_4)
        self.NearestNeighbor_graphicsView.setObjectName("NearestNeighbor_graphicsView")
        self.verticalLayout_6.addWidget(self.NearestNeighbor_graphicsView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LinearInterpolation_label = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LinearInterpolation_label.setFont(font)
        self.LinearInterpolation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.LinearInterpolation_label.setObjectName("LinearInterpolation_label")
        self.verticalLayout_7.addWidget(self.LinearInterpolation_label)
        self.LinearInterpolation_graphicsView = QtWidgets.QGraphicsView(self.tab_4)
        self.LinearInterpolation_graphicsView.setObjectName("LinearInterpolation_graphicsView")
        self.verticalLayout_7.addWidget(self.LinearInterpolation_graphicsView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.ZoomFactor_label = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ZoomFactor_label.setFont(font)
        self.ZoomFactor_label.setObjectName("ZoomFactor_label")
        self.horizontalLayout_4.addWidget(self.ZoomFactor_label)
        self.ZoomFactor_lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.ZoomFactor_lineEdit.setObjectName("ZoomFactor_lineEdit")
        self.horizontalLayout_4.addWidget(self.ZoomFactor_lineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Info_label_Zoomed = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Info_label_Zoomed.setFont(font)
        self.Info_label_Zoomed.setAlignment(QtCore.Qt.AlignCenter)
        self.Info_label_Zoomed.setObjectName("Info_label_Zoomed")
        self.verticalLayout_3.addWidget(self.Info_label_Zoomed)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser_Zoomed = QtWidgets.QTextBrowser(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Zoomed.sizePolicy().hasHeightForWidth())
        self.textBrowser_Zoomed.setSizePolicy(sizePolicy)
        self.textBrowser_Zoomed.setMaximumSize(QtCore.QSize(16777215, 115))
        self.textBrowser_Zoomed.setObjectName("textBrowser_Zoomed")
        self.horizontalLayout_2.addWidget(self.textBrowser_Zoomed)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.NearestNeighbor_Rotation_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NearestNeighbor_Rotation_label.setFont(font)
        self.NearestNeighbor_Rotation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.NearestNeighbor_Rotation_label.setObjectName("NearestNeighbor_Rotation_label")
        self.verticalLayout_8.addWidget(self.NearestNeighbor_Rotation_label)
        self.NearestNeighbor_Rotation_graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.NearestNeighbor_Rotation_graphicsView.setObjectName("NearestNeighbor_Rotation_graphicsView")
        self.verticalLayout_8.addWidget(self.NearestNeighbor_Rotation_graphicsView)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.LinearInterpolation_Rotation_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LinearInterpolation_Rotation_label.setFont(font)
        self.LinearInterpolation_Rotation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.LinearInterpolation_Rotation_label.setObjectName("LinearInterpolation_Rotation_label")
        self.verticalLayout_9.addWidget(self.LinearInterpolation_Rotation_label)
        self.LinearInterpolation_Rotation_graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.LinearInterpolation_Rotation_graphicsView.setObjectName("LinearInterpolation_Rotation_graphicsView")
        self.verticalLayout_9.addWidget(self.LinearInterpolation_Rotation_graphicsView)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.Rotation_Angle_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Rotation_Angle_label.setFont(font)
        self.Rotation_Angle_label.setObjectName("Rotation_Angle_label")
        self.horizontalLayout_6.addWidget(self.Rotation_Angle_label)
        self.Rotation_Angle_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.Rotation_Angle_lineEdit.setObjectName("Rotation_Angle_lineEdit")
        self.horizontalLayout_6.addWidget(self.Rotation_Angle_lineEdit)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.radioButton_Nearest = QtWidgets.QRadioButton(self.tab)
        self.radioButton_Nearest.setObjectName("radioButton_Nearest")
        self.horizontalLayout_6.addWidget(self.radioButton_Nearest)
        self.radioButton_Linear = QtWidgets.QRadioButton(self.tab)
        self.radioButton_Linear.setObjectName("radioButton_Linear")
        self.horizontalLayout_6.addWidget(self.radioButton_Linear)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Info_label_Rotated = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Info_label_Rotated.setFont(font)
        self.Info_label_Rotated.setAlignment(QtCore.Qt.AlignCenter)
        self.Info_label_Rotated.setObjectName("Info_label_Rotated")
        self.verticalLayout_4.addWidget(self.Info_label_Rotated)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.textBrowser_Rotated = QtWidgets.QTextBrowser(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Rotated.sizePolicy().hasHeightForWidth())
        self.textBrowser_Rotated.setSizePolicy(sizePolicy)
        self.textBrowser_Rotated.setMaximumSize(QtCore.QSize(16777215, 115))
        self.textBrowser_Rotated.setObjectName("textBrowser_Rotated")
        self.horizontalLayout_7.addWidget(self.textBrowser_Rotated)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.Shear_pushButton = QtWidgets.QPushButton(self.tab_2)
        self.Shear_pushButton.setObjectName("Shear_pushButton")
        self.horizontalLayout_8.addWidget(self.Shear_pushButton)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem15)
        self.Sheared_label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Sheared_label.setFont(font)
        self.Sheared_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Sheared_label.setObjectName("Sheared_label")
        self.verticalLayout_5.addWidget(self.Sheared_label)
        self.Shear_graphicsView = QtWidgets.QGraphicsView(self.tab_2)
        self.Shear_graphicsView.setObjectName("Shear_graphicsView")
        self.verticalLayout_5.addWidget(self.Shear_graphicsView)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem16, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem17, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem18, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        # self.gridLayout_11.setObjectName("gridLayout_11")
        # self.Equalize_pushButton = QtWidgets.QPushButton(self.tab_5)
        # self.Equalize_pushButton.setObjectName("Equalize_pushButton")
        # self.gridLayout_11.addWidget(self.Equalize_pushButton, 3, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem19, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem20, 5, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Image_for_Equliziation_label = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Image_for_Equliziation_label.setFont(font)
        self.Image_for_Equliziation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_for_Equliziation_label.setObjectName("Image_for_Equliziation_label")
        self.verticalLayout_10.addWidget(self.Image_for_Equliziation_label)
        self.Image_Brfore_EQ = MplWidget(self.tab_5)
        self.Image_Brfore_EQ.setMinimumSize(QtCore.QSize(400, 300))
        self.Image_Brfore_EQ.setObjectName("Image_Brfore_EQ")
        self.verticalLayout_10.addWidget(self.Image_Brfore_EQ)
        self.gridLayout_11.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Histogram_label = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Histogram_label.sizePolicy().hasHeightForWidth())
        self.Histogram_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Histogram_label.setFont(font)
        self.Histogram_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Histogram_label.setObjectName("Histogram_label")
        self.verticalLayout_16.addWidget(self.Histogram_label)
        self.Original_Histogram = MplWidget(self.tab_5)
        self.Original_Histogram.setMinimumSize(QtCore.QSize(400, 300))
        self.Original_Histogram.setObjectName("Original_Histogram")
        self.verticalLayout_16.addWidget(self.Original_Histogram)
        self.gridLayout_11.addLayout(self.verticalLayout_16, 5, 0, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Equalized_Histogram_label = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Equalized_Histogram_label.sizePolicy().hasHeightForWidth())
        self.Equalized_Histogram_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Equalized_Histogram_label.setFont(font)
        self.Equalized_Histogram_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Equalized_Histogram_label.setObjectName("Equalized_Histogram_label")
        self.verticalLayout_17.addWidget(self.Equalized_Histogram_label)
        self.EQ_Histogram = MplWidget(self.tab_5)
        self.EQ_Histogram.setMinimumSize(QtCore.QSize(400, 300))
        self.EQ_Histogram.setObjectName("EQ_Histogram")
        self.verticalLayout_17.addWidget(self.EQ_Histogram)
        self.gridLayout_11.addLayout(self.verticalLayout_17, 5, 2, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Equlized_Image_label = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Equlized_Image_label.setFont(font)
        self.Equlized_Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Equlized_Image_label.setObjectName("Equlized_Image_label")
        self.verticalLayout_15.addWidget(self.Equlized_Image_label)
        self.Image_After_EQ = MplWidget(self.tab_5)
        self.Image_After_EQ.setMinimumSize(QtCore.QSize(400, 300))
        self.Image_After_EQ.setObjectName("Image_After_EQ")
        self.verticalLayout_15.addWidget(self.Image_After_EQ)
        self.gridLayout_11.addLayout(self.verticalLayout_15, 0, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem21, 4, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem22, 4, 0, 1, 1)
        self.Show_Hist_pushButton = QtWidgets.QPushButton(self.tab_5)
        self.Show_Hist_pushButton.setObjectName("Show_Hist_pushButton")
        self.gridLayout_11.addWidget(self.Show_Hist_pushButton, 3, 0, 1, 1)
        # self.Equalize_Hist_pushButton = QtWidgets.QPushButton(self.tab_5)
        # self.Equalize_Hist_pushButton.setObjectName("Equalize_Hist_pushButton")
        # self.gridLayout_11.addWidget(self.Equalize_Hist_pushButton, 6, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem23, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.Salt_and_Paper_groupBox = QtWidgets.QGroupBox(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Salt_and_Paper_groupBox.setFont(font)
        self.Salt_and_Paper_groupBox.setObjectName("Salt_and_Paper_groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.Salt_and_Paper_groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Noised_image_label = QtWidgets.QLabel(self.Salt_and_Paper_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Noised_image_label.setFont(font)
        self.Noised_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Noised_image_label.setObjectName("Noised_image_label")
        self.verticalLayout_18.addWidget(self.Noised_image_label)
        self.Noised_image_graphicsView = QtWidgets.QGraphicsView(self.Salt_and_Paper_groupBox)
        self.Noised_image_graphicsView.setObjectName("Noised_image_graphicsView")
        self.verticalLayout_18.addWidget(self.Noised_image_graphicsView)
        self.horizontalLayout_12.addLayout(self.verticalLayout_18)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_12.addItem(spacerItem24)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Filtered_image_label = QtWidgets.QLabel(self.Salt_and_Paper_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Filtered_image_label.setFont(font)
        self.Filtered_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Filtered_image_label.setObjectName("Filtered_image_label")
        self.verticalLayout_19.addWidget(self.Filtered_image_label)
        self.Filtered_image_graphicsView = QtWidgets.QGraphicsView(self.Salt_and_Paper_groupBox)
        self.Filtered_image_graphicsView.setObjectName("Filtered_image_graphicsView")
        self.verticalLayout_19.addWidget(self.Filtered_image_graphicsView)
        self.horizontalLayout_12.addLayout(self.verticalLayout_19)
        self.gridLayout_15.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.Salt_and_Paper_groupBox, 2, 0, 1, 1)
        self.Sharpining_groupBox = QtWidgets.QGroupBox(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Sharpining_groupBox.setFont(font)
        self.Sharpining_groupBox.setObjectName("Sharpining_groupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Sharpining_groupBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Unsharped_image_label = QtWidgets.QLabel(self.Sharpining_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Unsharped_image_label.setFont(font)
        self.Unsharped_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Unsharped_image_label.setObjectName("Unsharped_image_label")
        self.verticalLayout_12.addWidget(self.Unsharped_image_label)
        self.Unsharped_image_graphicsView = QtWidgets.QGraphicsView(self.Sharpining_groupBox)
        self.Unsharped_image_graphicsView.setObjectName("Unsharped_image_graphicsView")
        self.verticalLayout_12.addWidget(self.Unsharped_image_graphicsView)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Filter_Size_label = QtWidgets.QLabel(self.Sharpining_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Filter_Size_label.setFont(font)
        self.Filter_Size_label.setObjectName("Filter_Size_label")
        self.horizontalLayout_10.addWidget(self.Filter_Size_label)
        self.Filter_Size_lineEdit = QtWidgets.QLineEdit(self.Sharpining_groupBox)
        self.Filter_Size_lineEdit.setObjectName("Filter_Size_lineEdit")
        self.horizontalLayout_10.addWidget(self.Filter_Size_lineEdit)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem25)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Sharped_image_label = QtWidgets.QLabel(self.Sharpining_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sharped_image_label.setFont(font)
        self.Sharped_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Sharped_image_label.setObjectName("Sharped_image_label")
        self.verticalLayout_14.addWidget(self.Sharped_image_label)
        self.Sharped_image_graphicsView = QtWidgets.QGraphicsView(self.Sharpining_groupBox)
        self.Sharped_image_graphicsView.setObjectName("Sharped_image_graphicsView")
        self.verticalLayout_14.addWidget(self.Sharped_image_graphicsView)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Edge_Factor_label = QtWidgets.QLabel(self.Sharpining_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Edge_Factor_label.setFont(font)
        self.Edge_Factor_label.setObjectName("Edge_Factor_label")
        self.horizontalLayout_11.addWidget(self.Edge_Factor_label)
        self.Edge_Factor_lineEdit = QtWidgets.QLineEdit(self.Sharpining_groupBox)
        self.Edge_Factor_lineEdit.setObjectName("Edge_Factor_lineEdit")
        self.horizontalLayout_11.addWidget(self.Edge_Factor_lineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.gridLayout_14.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Sharp_pushButton = QtWidgets.QPushButton(self.Sharpining_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sharp_pushButton.setFont(font)
        self.Sharp_pushButton.setObjectName("Sharp_pushButton")
        self.horizontalLayout_13.addWidget(self.Sharp_pushButton)
        self.Noise_pushButton = QtWidgets.QPushButton(self.Sharpining_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Noise_pushButton.setFont(font)
        self.Noise_pushButton.setObjectName("Noise_pushButton")
        self.horizontalLayout_13.addWidget(self.Noise_pushButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.Sharpining_groupBox, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem26, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem27)
        self.Filter_pushButton = QtWidgets.QPushButton(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Filter_pushButton.setFont(font)
        self.Filter_pushButton.setObjectName("Filter_pushButton")
        self.horizontalLayout_14.addWidget(self.Filter_pushButton)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem28)
        self.gridLayout_16.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Log_groupBox = QtWidgets.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Log_groupBox.setFont(font)
        self.Log_groupBox.setObjectName("Log_groupBox")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.Log_groupBox)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.Logged_Magnitiude_label = QtWidgets.QLabel(self.Log_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Logged_Magnitiude_label.setFont(font)
        self.Logged_Magnitiude_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Logged_Magnitiude_label.setObjectName("Logged_Magnitiude_label")
        self.verticalLayout_55.addWidget(self.Logged_Magnitiude_label)
        self.Logged_Magnitiude_graphicsView = QtWidgets.QGraphicsView(self.Log_groupBox)
        self.Logged_Magnitiude_graphicsView.setObjectName("Logged_Magnitiude_graphicsView")
        self.verticalLayout_55.addWidget(self.Logged_Magnitiude_graphicsView)
        self.Show_Logged_Magnitiude_pushButton = QtWidgets.QPushButton(self.Log_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Show_Logged_Magnitiude_pushButton.setFont(font)
        self.Show_Logged_Magnitiude_pushButton.setObjectName("Show_Logged_Magnitiude_pushButton")
        self.verticalLayout_55.addWidget(self.Show_Logged_Magnitiude_pushButton)
        self.horizontalLayout_37.addLayout(self.verticalLayout_55)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_37.addItem(spacerItem29)
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.Logged_Phase_label = QtWidgets.QLabel(self.Log_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Logged_Phase_label.setFont(font)
        self.Logged_Phase_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Logged_Phase_label.setObjectName("Logged_Phase_label")
        self.verticalLayout_56.addWidget(self.Logged_Phase_label)
        self.Logged_Phase_graphicsView = QtWidgets.QGraphicsView(self.Log_groupBox)
        self.Logged_Phase_graphicsView.setObjectName("Logged_Phase_graphicsView")
        self.verticalLayout_56.addWidget(self.Logged_Phase_graphicsView)
        self.Show_Logged_Phase_pushButton = QtWidgets.QPushButton(self.Log_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Show_Logged_Phase_pushButton.setFont(font)
        self.Show_Logged_Phase_pushButton.setObjectName("Show_Logged_Phase_pushButton")
        self.verticalLayout_56.addWidget(self.Show_Logged_Phase_pushButton)
        self.horizontalLayout_37.addLayout(self.verticalLayout_56)
        self.gridLayout_44.addLayout(self.horizontalLayout_37, 0, 0, 1, 1)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.gridLayout_44.addLayout(self.horizontalLayout_42, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.Log_groupBox, 2, 0, 1, 1)
        self.Original_groupBox = QtWidgets.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Original_groupBox.setFont(font)
        self.Original_groupBox.setObjectName("Original_groupBox")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.Original_groupBox)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.Original_Magnitiude_label = QtWidgets.QLabel(self.Original_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Original_Magnitiude_label.setFont(font)
        self.Original_Magnitiude_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Original_Magnitiude_label.setObjectName("Original_Magnitiude_label")
        self.verticalLayout_58.addWidget(self.Original_Magnitiude_label)
        self.Original_Magnitiude_graphicsView = QtWidgets.QGraphicsView(self.Original_groupBox)
        self.Original_Magnitiude_graphicsView.setObjectName("Original_Magnitiude_graphicsView")
        self.verticalLayout_58.addWidget(self.Original_Magnitiude_graphicsView)
        self.Show_Original_Magnitiude_pushButton = QtWidgets.QPushButton(self.Original_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Show_Original_Magnitiude_pushButton.setFont(font)
        self.Show_Original_Magnitiude_pushButton.setObjectName("Show_Original_Magnitiude_pushButton")
        self.verticalLayout_58.addWidget(self.Show_Original_Magnitiude_pushButton)
        self.verticalLayout_57.addLayout(self.verticalLayout_58)
        self.horizontalLayout_38.addLayout(self.verticalLayout_57)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_38.addItem(spacerItem30)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.Original_Phase_label = QtWidgets.QLabel(self.Original_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Original_Phase_label.setFont(font)
        self.Original_Phase_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Original_Phase_label.setObjectName("Original_Phase_label")
        self.verticalLayout_60.addWidget(self.Original_Phase_label)
        self.Original_Phase_graphicsView = QtWidgets.QGraphicsView(self.Original_groupBox)
        self.Original_Phase_graphicsView.setObjectName("Original_Phase_graphicsView")
        self.verticalLayout_60.addWidget(self.Original_Phase_graphicsView)
        self.Show_Original_Phase_pushButton = QtWidgets.QPushButton(self.Original_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Show_Original_Phase_pushButton.setFont(font)
        self.Show_Original_Phase_pushButton.setObjectName("Show_Original_Phase_pushButton")
        self.verticalLayout_60.addWidget(self.Show_Original_Phase_pushButton)
        self.verticalLayout_59.addLayout(self.verticalLayout_60)
        self.horizontalLayout_38.addLayout(self.verticalLayout_59)
        self.gridLayout_46.addLayout(self.horizontalLayout_38, 0, 0, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_46, 0, 0, 1, 1)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.gridLayout_45.addLayout(self.horizontalLayout_41, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.Original_groupBox, 0, 0, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.Sharpining_groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Sharpining_groupBox_2.setFont(font)
        self.Sharpining_groupBox_2.setObjectName("Sharpining_groupBox_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.Sharpining_groupBox_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Blur_pushButton = QtWidgets.QPushButton(self.Sharpining_groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Blur_pushButton.setFont(font)
        self.Blur_pushButton.setObjectName("Blur_pushButton")
        self.horizontalLayout_26.addWidget(self.Blur_pushButton)
        self.gridLayout_21.addLayout(self.horizontalLayout_26, 2, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.Unsharped_image_Inverse = QtWidgets.QLabel(self.Sharpining_groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Unsharped_image_Inverse.setFont(font)
        self.Unsharped_image_Inverse.setAlignment(QtCore.Qt.AlignCenter)
        self.Unsharped_image_Inverse.setObjectName("Unsharped_image_Inverse")
        self.verticalLayout_30.addWidget(self.Unsharped_image_Inverse)
        self.Unsharped_image_graphicsView_1 = QtWidgets.QGraphicsView(self.Sharpining_groupBox_2)
        self.Unsharped_image_graphicsView_1.setObjectName("Unsharped_image_graphicsView_1")
        self.verticalLayout_30.addWidget(self.Unsharped_image_graphicsView_1)
        self.verticalLayout_29.addLayout(self.verticalLayout_30)
        self.horizontalLayout_23.addLayout(self.verticalLayout_29)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_23.addItem(spacerItem31)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.Blurred_image_label_Fourier = QtWidgets.QLabel(self.Sharpining_groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Blurred_image_label_Fourier.setFont(font)
        self.Blurred_image_label_Fourier.setAlignment(QtCore.Qt.AlignCenter)
        self.Blurred_image_label_Fourier.setObjectName("Blurred_image_label_Fourier")
        self.verticalLayout_32.addWidget(self.Blurred_image_label_Fourier)
        self.Blurred_image_graphicsView = QtWidgets.QGraphicsView(self.Sharpining_groupBox_2)
        self.Blurred_image_graphicsView.setObjectName("Blurred_image_graphicsView")
        self.verticalLayout_32.addWidget(self.Blurred_image_graphicsView)
        self.verticalLayout_31.addLayout(self.verticalLayout_32)
        self.horizontalLayout_23.addLayout(self.verticalLayout_31)
        self.gridLayout_22.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.Filter_Size_label_1 = QtWidgets.QLabel(self.Sharpining_groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Filter_Size_label_1.setFont(font)
        self.Filter_Size_label_1.setObjectName("Filter_Size_label_1")
        self.horizontalLayout_24.addWidget(self.Filter_Size_label_1)
        self.Filter_Size_Fourier_lineEdit = QtWidgets.QLineEdit(self.Sharpining_groupBox_2)
        self.Filter_Size_Fourier_lineEdit.setObjectName("Filter_Size_Fourier_lineEdit")
        self.horizontalLayout_24.addWidget(self.Filter_Size_Fourier_lineEdit)
        self.gridLayout_21.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.Sharpining_groupBox_2, 0, 0, 1, 2)
        self.Salt_and_Paper_groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Salt_and_Paper_groupBox_2.setFont(font)
        self.Salt_and_Paper_groupBox_2.setObjectName("Salt_and_Paper_groupBox_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.Salt_and_Paper_groupBox_2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.Blurred_Fourier_image_label = QtWidgets.QLabel(self.Salt_and_Paper_groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Blurred_Fourier_image_label.setFont(font)
        self.Blurred_Fourier_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Blurred_Fourier_image_label.setObjectName("Blurred_Fourier_image_label")
        self.verticalLayout_27.addWidget(self.Blurred_Fourier_image_label)
        self.Blurred_Fourier_image_graphicsView = QtWidgets.QGraphicsView(self.Salt_and_Paper_groupBox_2)
        self.Blurred_Fourier_image_graphicsView.setObjectName("Blurred_Fourier_image_graphicsView")
        self.verticalLayout_27.addWidget(self.Blurred_Fourier_image_graphicsView)
        self.horizontalLayout_22.addLayout(self.verticalLayout_27)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_22.addItem(spacerItem32)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.Differnce_image_label = QtWidgets.QLabel(self.Salt_and_Paper_groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Differnce_image_label.setFont(font)
        self.Differnce_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Differnce_image_label.setObjectName("Differnce_image_label")
        self.verticalLayout_28.addWidget(self.Differnce_image_label)
        self.Difference_image_graphicsView = QtWidgets.QGraphicsView(self.Salt_and_Paper_groupBox_2)
        self.Difference_image_graphicsView.setObjectName("Difference_image_graphicsView")
        self.verticalLayout_28.addWidget(self.Difference_image_graphicsView)
        self.horizontalLayout_22.addLayout(self.verticalLayout_28)
        self.gridLayout_20.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.Salt_and_Paper_groupBox_2, 2, 0, 1, 2)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.Fourier_pushButton = QtWidgets.QPushButton(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Fourier_pushButton.setFont(font)
        self.Fourier_pushButton.setObjectName("Fourier_pushButton")
        self.gridLayout_23.addWidget(self.Fourier_pushButton, 0, 0, 1, 1)
        self.Difference_pushButton = QtWidgets.QPushButton(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Difference_pushButton.setFont(font)
        self.Difference_pushButton.setObjectName("Difference_pushButton")
        self.gridLayout_23.addWidget(self.Difference_pushButton, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 3, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(921, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem33, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_78 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_78.setObjectName("gridLayout_78")
        self.Moire_Pattern_groupBox = QtWidgets.QGroupBox(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Moire_Pattern_groupBox.setFont(font)
        self.Moire_Pattern_groupBox.setObjectName("Moire_Pattern_groupBox")
        self.gridLayout_76 = QtWidgets.QGridLayout(self.Moire_Pattern_groupBox)
        self.gridLayout_76.setObjectName("gridLayout_76")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.Moire_Filter_pushButton = QtWidgets.QPushButton(self.Moire_Pattern_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Moire_Filter_pushButton.setFont(font)
        self.Moire_Filter_pushButton.setObjectName("Moire_Filter_pushButton")
        self.horizontalLayout_67.addWidget(self.Moire_Filter_pushButton)
        self.gridLayout_76.addLayout(self.horizontalLayout_67, 2, 0, 1, 1)
        self.gridLayout_77 = QtWidgets.QGridLayout()
        self.gridLayout_77.setObjectName("gridLayout_77")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.verticalLayout_97 = QtWidgets.QVBoxLayout()
        self.verticalLayout_97.setObjectName("verticalLayout_97")
        self.verticalLayout_98 = QtWidgets.QVBoxLayout()
        self.verticalLayout_98.setObjectName("verticalLayout_98")
        self.Moire_pattern_image = QtWidgets.QLabel(self.Moire_Pattern_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Moire_pattern_image.setFont(font)
        self.Moire_pattern_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Moire_pattern_image.setObjectName("Moire_pattern_image")
        self.verticalLayout_98.addWidget(self.Moire_pattern_image)
        self.Moire_pattern_image_graphicsView = QtWidgets.QGraphicsView(self.Moire_Pattern_groupBox)
        self.Moire_pattern_image_graphicsView.setObjectName("Moire_pattern_image_graphicsView")
        self.verticalLayout_98.addWidget(self.Moire_pattern_image_graphicsView)
        self.verticalLayout_97.addLayout(self.verticalLayout_98)
        self.horizontalLayout_68.addLayout(self.verticalLayout_97)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_68.addItem(spacerItem34)
        self.verticalLayout_99 = QtWidgets.QVBoxLayout()
        self.verticalLayout_99.setObjectName("verticalLayout_99")
        self.verticalLayout_100 = QtWidgets.QVBoxLayout()
        self.verticalLayout_100.setObjectName("verticalLayout_100")
        self.Filtered_Image_label = QtWidgets.QLabel(self.Moire_Pattern_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Filtered_Image_label.setFont(font)
        self.Filtered_Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Filtered_Image_label.setObjectName("Filtered_Image_label")
        self.verticalLayout_100.addWidget(self.Filtered_Image_label)
        self.Filtered_Moire_image_graphicsView = QtWidgets.QGraphicsView(self.Moire_Pattern_groupBox)
        self.Filtered_Moire_image_graphicsView.setObjectName("Filtered_Moire_image_graphicsView")
        self.verticalLayout_100.addWidget(self.Filtered_Moire_image_graphicsView)
        self.verticalLayout_99.addLayout(self.verticalLayout_100)
        self.horizontalLayout_68.addLayout(self.verticalLayout_99)
        self.gridLayout_77.addLayout(self.horizontalLayout_68, 0, 0, 1, 1)
        self.gridLayout_76.addLayout(self.gridLayout_77, 0, 0, 1, 1)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        # self.Filter_Moire_label = QtWidgets.QLabel(self.Moire_Pattern_groupBox)
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # font.setBold(True)
        # font.setWeight(75)
        # self.Filter_Moire_label.setFont(font)
        # self.Filter_Moire_label.setObjectName("Filter_Moire_label")
        # self.horizontalLayout_69.addWidget(self.Filter_Moire_label)
        # self.Moire_lineEdit = QtWidgets.QLineEdit(self.Moire_Pattern_groupBox)
        # self.Moire_lineEdit.setObjectName("Moire_lineEdit")
        # self.horizontalLayout_69.addWidget(self.Moire_lineEdit)
        self.gridLayout_76.addLayout(self.horizontalLayout_69, 1, 0, 1, 1)
        self.gridLayout_78.addWidget(self.Moire_Pattern_groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.gridLayout_79.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtWidgets.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.menuFile.addAction(self.actionBrowse)
        self.menubar.addAction(self.menuFile.menuAction())

        self.scene = QGraphicsScene()
        self.Image_graphicsView.setScene(self.scene)

        self.sceneNearestNeighbor_Zoomed=QGraphicsScene()
        self.NearestNeighbor_graphicsView.setScene(self.sceneNearestNeighbor_Zoomed)

        self.sceneLinearInerpolation_Zoomed=QGraphicsScene()
        self.LinearInterpolation_graphicsView.setScene(self.sceneLinearInerpolation_Zoomed)

        self.sceneNearestNeighbor_Rotation=QGraphicsScene()
        self.NearestNeighbor_Rotation_graphicsView.setScene(self.sceneNearestNeighbor_Rotation)

        self.sceneLinearInterpolation_Rotation=QGraphicsScene()
        self.LinearInterpolation_Rotation_graphicsView.setScene(self.sceneLinearInterpolation_Rotation)

        self.sceneShearedImage=QGraphicsScene()
        self.Shear_graphicsView.setScene(self.sceneShearedImage)

        self.sceneUnsharpedImage=QGraphicsScene()
        self.Unsharped_image_graphicsView.setScene(self.sceneUnsharpedImage)

        self.sceneSharpedImage=QGraphicsScene()
        self.Sharped_image_graphicsView.setScene(self.sceneSharpedImage)

        self.sceneNoisedImage=QGraphicsScene()
        self.Noised_image_graphicsView.setScene(self.sceneNoisedImage)

        self.sceneFilteredImage=QGraphicsScene()
        self.Filtered_image_graphicsView.setScene(self.sceneFilteredImage)

        self.sceneoriginalMag=QGraphicsScene()
        self.Original_Magnitiude_graphicsView.setScene(self.sceneoriginalMag)

        self.sceneoriginalPhase=QGraphicsScene()
        self.Original_Phase_graphicsView.setScene(self.sceneoriginalPhase)

        self.sceneloggedMag=QGraphicsScene()
        self.Logged_Magnitiude_graphicsView.setScene(self.sceneloggedMag)

        self.sceneloggedPhase=QGraphicsScene()
        self.Logged_Phase_graphicsView.setScene(self.sceneloggedPhase)

        self.sceneUnsharpedFourierImage=QGraphicsScene()
        self.Unsharped_image_graphicsView_1.setScene(self.sceneUnsharpedFourierImage)

        self.sceneBlurredImage=QGraphicsScene()
        self.Blurred_image_graphicsView.setScene(self.sceneBlurredImage)

        self.sceneBlurredFourierImage=QGraphicsScene()
        self.Blurred_Fourier_image_graphicsView.setScene(self.sceneBlurredFourierImage)
        
        self.sceneDifferenceImage=QGraphicsScene()
        self.Difference_image_graphicsView.setScene(self.sceneDifferenceImage)

        self.sceneMoirePatternImage=QGraphicsScene()
        self.Moire_pattern_image_graphicsView.setScene(self.sceneMoirePatternImage)

        self.sceneFilteredMoireImage=QGraphicsScene()
        self.Filtered_Moire_image_graphicsView.setScene(self.sceneFilteredMoireImage)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Image_label.setText(_translate("MainWindow", "Image"))
        self.Info_label.setText(_translate("MainWindow", "Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Image Viewer"))
        self.NearestNeighbor_label.setText(_translate("MainWindow", "Nearest Neighbor"))
        self.LinearInterpolation_label.setText(_translate("MainWindow", "Linear Interpolation"))
        self.ZoomFactor_label.setText(_translate("MainWindow", "Zoom Factor"))
        self.Info_label_Zoomed.setText(_translate("MainWindow", "Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Zoom In/Out"))
        self.NearestNeighbor_Rotation_label.setText(_translate("MainWindow", "Nearest Neighbor"))
        self.LinearInterpolation_Rotation_label.setText(_translate("MainWindow", "Linear Interpolation"))
        self.Rotation_Angle_label.setText(_translate("MainWindow", "Rotation Angle"))
        self.label.setText(_translate("MainWindow", "Default (AntiClockWise) For ClockWise Please Enter (-ve) Value"))
        self.radioButton_Nearest.setText(_translate("MainWindow", "Nearest"))
        self.radioButton_Linear.setText(_translate("MainWindow", "Linear"))
        self.Info_label_Rotated.setText(_translate("MainWindow", "Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Rotating"))
        self.Shear_pushButton.setText(_translate("MainWindow", "Shear"))
        self.Sheared_label.setText(_translate("MainWindow", "Sheared Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Shearing"))
        # self.Equalize_pushButton.setText(_translate("MainWindow", "Equalize Image!"))
        self.Image_for_Equliziation_label.setText(_translate("MainWindow", "Image"))
        self.Histogram_label.setText(_translate("MainWindow", "Histogram"))
        self.Equalized_Histogram_label.setText(_translate("MainWindow", "Equalized Histogram"))
        self.Equlized_Image_label.setText(_translate("MainWindow", "Equalized Image"))
        self.Show_Hist_pushButton.setText(_translate("MainWindow", "Show Histogram"))
        # self.Equalize_Hist_pushButton.setText(_translate("MainWindow", "Equalize Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Histogram "))
        self.Salt_and_Paper_groupBox.setTitle(_translate("MainWindow", "Salt & Paper Noise"))
        self.Noised_image_label.setText(_translate("MainWindow", "Noised Image"))
        self.Filtered_image_label.setText(_translate("MainWindow", "Filtered Image"))
        self.Sharpining_groupBox.setTitle(_translate("MainWindow", "Sharpining"))
        self.Unsharped_image_label.setText(_translate("MainWindow", "Original Image"))
        self.Filter_Size_label.setText(_translate("MainWindow", "Filter Size "))
        self.Sharped_image_label.setText(_translate("MainWindow", "Sharpned Image"))
        self.Edge_Factor_label.setText(_translate("MainWindow", "Edge Factor"))
        self.Sharp_pushButton.setText(_translate("MainWindow", "Sharp !"))
        self.Noise_pushButton.setText(_translate("MainWindow", "Add Noise !"))
        self.Filter_pushButton.setText(_translate("MainWindow", "Filter !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Filtering"))
        self.Log_groupBox.setTitle(_translate("MainWindow", "Log"))
        self.Logged_Magnitiude_label.setText(_translate("MainWindow", "Logged Magnitiude"))
        self.Show_Logged_Magnitiude_pushButton.setText(_translate("MainWindow", "Show Magnitiude !"))
        self.Logged_Phase_label.setText(_translate("MainWindow", "Filtered Image"))
        self.Show_Logged_Phase_pushButton.setText(_translate("MainWindow", "Show Phase !"))
        self.Original_groupBox.setTitle(_translate("MainWindow", "Original"))
        self.Original_Magnitiude_label.setText(_translate("MainWindow", "Original Magnitiude"))
        self.Show_Original_Magnitiude_pushButton.setText(_translate("MainWindow", "Show Magnitiude !"))
        self.Original_Phase_label.setText(_translate("MainWindow", "Original Phase"))
        self.Show_Original_Phase_pushButton.setText(_translate("MainWindow", "Show Phase !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Fourier"))
        self.Sharpining_groupBox_2.setTitle(_translate("MainWindow", "Spatial"))
        self.Blur_pushButton.setText(_translate("MainWindow", "Blur !"))
        self.Unsharped_image_Inverse.setText(_translate("MainWindow", "Original Image"))
        self.Blurred_image_label_Fourier.setText(_translate("MainWindow", "Blurred Image"))
        self.Filter_Size_label_1.setText(_translate("MainWindow", "Filter Size "))
        self.Salt_and_Paper_groupBox_2.setTitle(_translate("MainWindow", "Fourier"))
        self.Blurred_Fourier_image_label.setText(_translate("MainWindow", "Blurred Fourier Image"))
        self.Differnce_image_label.setText(_translate("MainWindow", "Difference"))
        self.Fourier_pushButton.setText(_translate("MainWindow", "Fourier"))
        self.Difference_pushButton.setText(_translate("MainWindow", "Difference"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Inverse Fourier"))
        self.Moire_Pattern_groupBox.setTitle(_translate("MainWindow", "Moire Pattern"))
        self.Moire_Filter_pushButton.setText(_translate("MainWindow", "Filter !"))
        self.Moire_pattern_image.setText(_translate("MainWindow", "Moire Pattern"))
        self.Filtered_Image_label.setText(_translate("MainWindow", "Filtered Image"))
        # self.Filter_Moire_label.setText(_translate("MainWindow", "Filter Size "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Moire Pattern"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionBrowse.setText(_translate("MainWindow", "Browse..."))
        self.actionBrowse.setShortcut(_translate("MainWindow", "Ctrl+N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
